export const initialState = {
  style: null,
  buyer: "",
  brandName: "",
  season: "",
  itemQuantity: "",
  material: null,
  ratio: null,
  fabricType: "",
  yarnCount: null,
  count: "",
  ppiEpi: "",
  gsm: "",
  yarnDyed: null,
  dyedType: null,
  solidDyed: null,
  DyedRegularFinishing: null,
  dyedSpecial: null,
  dyedCoating: null,
  printType: null,
  printRoute: null,
  printRegularFinishing: null,
  printSpecial: null,
  printCoating: null,
};
